USE quotation_db;

CREATE TABLE IF NOT EXISTS customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(20) UNIQUE NOT NULL COMMENT 'รหัสลูกค้า/ผู้ขาย (CAxxx / Pxxxx)',
    name VARCHAR(255) NOT NULL COMMENT 'ชื่อลูกค้า/ผู้ขาย',
    pic_code VARCHAR(50) COMMENT 'รหัส PIC',
    tax_id VARCHAR(50) COMMENT 'เลขประจำตัวผู้เสียภาษีอากร',
    group_name VARCHAR(100) COMMENT 'ชื่อกลุ่ม',
    level_group VARCHAR(50) COMMENT 'ชื่อกลุ่มระดับลูกค้า/ผู้ขาย',
    contact_person VARCHAR(255) COMMENT 'ผู้ติดต่อ',
    address_1 TEXT COMMENT 'ที่อยู่ 1',
    email VARCHAR(255) COMMENT 'อีเมล',
    phone VARCHAR(50) COMMENT 'โทรศัพท์',
    all_contacts TEXT COMMENT 'รายชื่อผู้ติดต่อทั้งหมด',
    remark TEXT COMMENT 'หมายเหตุ',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'วันที่สร้าง',
    created_by VARCHAR(100) COMMENT 'ผู้สร้าง',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'วันที่แก้ไขล่าสุด',
    district VARCHAR(100) COMMENT 'อำเภอ',
    province VARCHAR(100) COMMENT 'จังหวัด',
    is_domestic VARCHAR(50) DEFAULT 'ในประเทศ' COMMENT 'ลูกค้าในประเทศ/ต่างประเทศ',
    lead_source VARCHAR(100) COMMENT 'แหล่งที่มาชื่อ',
    sales_region VARCHAR(100) COMMENT 'เขตการขาย',
    credit_days INT DEFAULT 0 COMMENT 'เครดิต (วัน)',
    credit_limit DECIMAL(15, 2) DEFAULT 0.00 COMMENT 'วงเงิน',
    industry_type VARCHAR(100) COMMENT 'ประเภทอุตสาหกรรม',
    company_name_additional VARCHAR(255) COMMENT 'ชื่อบริษัท (เพิ่มเติม)',
    sales_remark TEXT COMMENT 'Sales RemarB',
    type VARCHAR(50) COMMENT 'Type',
    category VARCHAR(50) COMMENT 'Catagory',
    area VARCHAR(100) COMMENT 'Area'
);
